---
abstract: 'memcached backend'
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
  MooseX::AttributeHelpers: 0.22
  Test::MockObject: 1.09
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: KiokuDB-Backend-Memcached
no_index:
  directory:
    - inc
    - t
requires:
  KiokuDB: 0.24
  Moose: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
